#!/usr/bin/env bash
# tests/test_auto_discovery.sh — Tests zero-prompt auto-discovery engine
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

passed=0
failed=0

pass() {
    printf "  \033[32m✔\033[0m %s\n" "$1"
    passed=$((passed + 1))
}

fail() {
    printf "  \033[31m✖\033[0m %s: %s\n" "$1" "$2"
    failed=$((failed + 1))
}

echo "=== Running tests/test_auto_discovery.sh ==="

# 1. Setup isolated sandbox environment
export GITSETU_TEST=1
SANDBOX=$(mktemp -d "${TMPDIR:-/tmp}/gitsetu-auto-test.XXXXXX")
if [[ "${OSTYPE:-}" == "msys"* ]] || [[ "${OSTYPE:-}" == "cygwin"* ]]; then
    SANDBOX=$(cd "$SANDBOX" && pwd -W)
else
    SANDBOX=$(cd "$SANDBOX" && pwd -P)
fi
export HOME="$SANDBOX"
export XDG_CONFIG_HOME="$SANDBOX/.config"

mkdir -p "$SANDBOX/.ssh"
mkdir -p "$SANDBOX/work"

# Create pre-existing global git config
git config --file "$SANDBOX/.gitconfig" user.name "Alex Developer"
git config --file "$SANDBOX/.gitconfig" user.email "alex@example.com"

# Create dummy mock keys
touch "$SANDBOX/.ssh/id_ed25519_global"
touch "$SANDBOX/.ssh/id_ed25519_global.pub"
chmod 600 "$SANDBOX/.ssh/id_ed25519_global"
echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAA alex@example.com" > "$SANDBOX/.ssh/id_ed25519_global.pub"

touch "$SANDBOX/.ssh/id_ed25519_work"
touch "$SANDBOX/.ssh/id_ed25519_work.pub"
chmod 600 "$SANDBOX/.ssh/id_ed25519_work"
echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAA alex@company.com" > "$SANDBOX/.ssh/id_ed25519_work.pub"

# 2. Test auto-discovery with --dry-run
dry_out=$("$REPO_DIR/gitsetu" setup --auto --dry-run < /dev/null 2>&1 || true)
if echo "$dry_out" | grep -qi "DRY RUN MODE"; then
    pass "setup --auto --dry-run respects dry run mode"
else
    fail "auto dry-run" "missing dry run notice"
fi

if echo "$dry_out" | grep -qi "Zero-Prompt Auto-Discovery Blueprint"; then
    pass "setup --auto discovers and displays blueprint header"
else
    fail "auto blueprint display" "blueprint header not shown in dry-run"
fi

# Ensure dry run did not write profiles.conf
if [ ! -f "$SANDBOX/.config/gitsetu/profiles.conf" ]; then
    pass "setup --auto --dry-run writes zero config files"
else
    fail "auto dry-run isolation" "profiles.conf unexpectedly created in dry run"
fi

# 3. Test actual live setup --auto (stdin from /dev/null ensures zero blocking prompts)
auto_out=$("$REPO_DIR/gitsetu" setup --auto < /dev/null 2>&1 || true)
if echo "$auto_out" | grep -qi "Setup complete"; then
    pass "setup --auto executes non-interactively without prompt blocking"
else
    fail "auto execution" "failed with output: $auto_out"
fi

# 4. Verify generated state
PROFILES_CONF="$SANDBOX/.config/gitsetu/profiles.conf"
if [ -f "$PROFILES_CONF" ]; then
    pass "profiles.conf successfully generated by auto setup"
    if grep -q "^global:" "$PROFILES_CONF" && grep -q "^work:" "$PROFILES_CONF"; then
        pass "auto-discovery detected and registered both global and work profiles"
    else
        fail "profiles registry" "profiles.conf missing expected profiles"
    fi
else
    fail "profiles.conf" "registry file missing"
fi

# 5. Verify ~/.gitconfig was modified with includeIf
if grep -q 'includeIf.*gitdir.*work' "$SANDBOX/.gitconfig"; then
    pass "~/.gitconfig contains auto-configured includeIf directive for work"
else
    fail "gitconfig includeIf" "work includeIf directive not found"
fi

# 6. Verify ~/.ssh/config includes managed block
if [ -f "$SANDBOX/.ssh/config" ] && grep -q "Include.*gitsetu" "$SANDBOX/.ssh/config"; then
    pass "~/.ssh/config contains managed gitsetu Include"
else
    fail "ssh config" "~/.ssh/config missing gitsetu Include"
fi

# 7. Test init alias with --auto
SANDBOX2=$(mktemp -d "${TMPDIR:-/tmp}/gitsetu-init-test.XXXXXX")
if [[ "${OSTYPE:-}" == "msys"* ]] || [[ "${OSTYPE:-}" == "cygwin"* ]]; then
    SANDBOX2=$(cd "$SANDBOX2" && pwd -W)
else
    SANDBOX2=$(cd "$SANDBOX2" && pwd -P)
fi
export HOME="$SANDBOX2"
export XDG_CONFIG_HOME="$SANDBOX2/.config"
git config --file "$SANDBOX2/.gitconfig" user.name "Init Tester"
git config --file "$SANDBOX2/.gitconfig" user.email "init@example.com"

init_out=$("$REPO_DIR/gitsetu" init --auto < /dev/null 2>&1 || true)
if echo "$init_out" | grep -qi "Setup complete"; then
    pass "gitsetu init --auto alias operates identically to setup --auto"
else
    fail "init alias" "init --auto failed to complete: $init_out"
fi

# Cleanup
rm -rf "$SANDBOX" "$SANDBOX2"

echo ""
echo "Auto-discovery tests: $passed passed, $failed failed, $((passed + failed)) total"
if [ "$failed" -gt 0 ]; then
    exit 1
fi
