#!/usr/bin/env bash
# lib/gitconfig.sh — Git configuration generation (global + per-profile)
#
# Manages ~/.gitconfig (global) and ~/.config/gitsetu/profiles/<label>.gitconfig
# Uses managed block markers for idempotent updates.
# Bash 3.2 compatible.

# ------------------------------------------------------------------------------
# build_global_gitconfig_block — Generate the managed block for ~/.gitconfig
#
# Includes:
#   - Default [user] section (name, email)
#   - Default [core] sshCommand
#   - [init] defaultBranch = main
#   - [includeIf] entries for each non-default profile
#
# Usage: block=$(build_global_gitconfig_block)
# ------------------------------------------------------------------------------
build_global_gitconfig_block() {
    local gitdir_kw
    gitdir_kw=$(get_gitdir_keyword)

    # Start with header and default user
    cat <<EOF
${GITSETU_MANAGED_START}
# Generated by gitsetu v${GITSETU_VERSION} on $(date +%Y-%m-%d)
# Do not edit between managed markers — gitsetu will overwrite on re-run.
# Everything outside these markers is preserved.

[user]
    useConfigOnly = true

[init]
    defaultBranch = main
EOF

    # If a global fallback profile exists (index 0 with empty dir), include it as the base identity
    if [[ "$PROFILE_COUNT" -gt 0 ]] && [[ -z "${PROFILE_DIRS[0]}" ]]; then
        local global_label="${PROFILE_LABELS[0]}"
        local global_path="${GITSETU_PROFILES_DIR}/${global_label}.gitconfig"
        global_path=$(normalize_path "$global_path")
        local escaped_global_path="${global_path//\\/\\\\}"
        escaped_global_path="${escaped_global_path//\"/\\\"}"
        cat <<EOF

[include]
    path = "${escaped_global_path}"
EOF
    fi

    if [[ "$GITSETU_OS" == "gitbash" ]]; then
        cat <<EOF

[credential]
    helper = manager
EOF
    else
        cat <<EOF

[credential]
    helper = "${GITSETU_SCRIPT_DIR}/gitsetu credential"
EOF
    fi

    # Add safe.directory for each non-default profile (solves VirtualBox/WSL dubious ownership)
    local has_safe=0
    local i
    for (( i=0; i<PROFILE_COUNT; i++ )); do
        local dir="${PROFILE_DIRS[$i]}"
        if [[ -n "$dir" ]]; then
            dir=$(normalize_path "$dir")
            if [[ "$dir" != */ ]]; then
                dir="${dir}/"
            fi
            
            if [[ "$has_safe" -eq 0 ]]; then
                printf '\n[safe]\n'
                has_safe=1
            fi
            # Sanitize newlines to prevent Git INI format corruption
            dir="${dir//$'\n'/}"
            
            local escaped_safe_dir="${dir//\\/\\\\}"
            escaped_safe_dir="${escaped_safe_dir//\"/\\\"}"
            printf '    directory = "%s*"\n' "$escaped_safe_dir"
        fi
    done

    # Add includeIf for each non-default profile
    local i
    for (( i=0; i<PROFILE_COUNT; i++ )); do
        local label="${PROFILE_LABELS[$i]}"
        local dir="${PROFILE_DIRS[$i]}"

        if [[ -n "$dir" ]]; then
            dir=$(normalize_path "$dir")
            # Ensure trailing slash for gitdir matching
            if [[ "$dir" != */ ]]; then
                dir="${dir}/"
            fi
            
            # Sanitize newlines to prevent Git INI format corruption
            dir="${dir//$'\n'/}"
            
            local escaped_dir="${dir//\\/\\\\}"
            escaped_dir="${escaped_dir//\"/\\\"}"

            local path="${GITSETU_PROFILES_DIR}/${label}.gitconfig"
            path=$(normalize_path "$path")
            local escaped_path="${path//\\/\\\\}"
            escaped_path="${escaped_path//\"/\\\"}"

            cat <<EOF

[includeIf "${gitdir_kw}${escaped_dir}"]
    path = "${escaped_path}"
EOF
        fi
    done

    # Close managed block
    printf '%s\n' "${GITSETU_MANAGED_END}"
}

# ------------------------------------------------------------------------------
# write_global_gitconfig — Write/update ~/.gitconfig
#
# Strategy:
#   - If ~/.gitconfig exists with non-managed content: PRESERVE it,
#     only replace the managed block
#   - If ~/.gitconfig exists with managed block: replace managed block
#   - If no ~/.gitconfig: create fresh with only the managed block
#
# Usage: write_global_gitconfig
# ------------------------------------------------------------------------------
write_global_gitconfig() {
    local gitconfig="$HOME/.gitconfig"
    local managed_block
    managed_block=$(build_global_gitconfig_block)

    # Dry run
    if [[ "$GITSETU_DRY_RUN" -eq 1 ]]; then
        print_info "[DRY RUN] Would update: $gitconfig"
        print_info "[DRY RUN] Managed block contents:"
        local line
        while IFS= read -r line; do
            printf >&2 '    %s\n' "$line"
        done < <(printf '%s\n' "$managed_block")
        return 0
    fi

    # Backup existing
    if [[ -f "$gitconfig" ]]; then
        backup_file "$gitconfig"
    fi

    if [[ -f "$gitconfig" ]] && grep -q "\[gitsetu:managed:start\]" "$gitconfig" 2>/dev/null; then
        # File exists WITH managed block → replace it
        local tmp_file
        tmp_file=$(mktemp "${gitconfig}.tmp.XXXXXX")
        GITSETU_CLEANUP_FILES+=("$tmp_file")
        export MANAGED_BLOCK="$managed_block"
        awk '
            BEGIN { in_block=0; buffer=""; written=0 }
            /\[gitsetu:managed:start\]/ {
                if (!written) {
                    in_block=1
                    buffer = $0 "\n"
                    next
                }
            }
            in_block {
                buffer = buffer $0 "\n"
                if (/\[gitsetu:managed:end\]/) {
                    print ENVIRON["MANAGED_BLOCK"]
                    in_block=0
                    written=1
                    buffer=""
                }
                next
            }
            !in_block { print }
            END {
                if (in_block) {
                    printf "%s", buffer
                }
                if (!written) {
                    print "\n" ENVIRON["MANAGED_BLOCK"]
                }
            }
        ' "$gitconfig" > "$tmp_file"

        mv "$tmp_file" "$gitconfig"
        unset MANAGED_BLOCK
        print_success "Updated managed block in: $gitconfig"

    elif [[ -f "$gitconfig" ]]; then
        # File exists WITHOUT managed block → append
        printf '\n%s\n' "$managed_block" >> "$gitconfig"
        print_success "Appended managed block to: $gitconfig"

    else
        # No file → create fresh
        printf '%s\n' "$managed_block" > "$gitconfig"
        print_success "Created: $gitconfig"
    fi
}

# ------------------------------------------------------------------------------
# build_profile_gitconfig — Generate a per-profile gitconfig
#
# Contains [user] and [core] sshCommand specific to this profile.
# This file is referenced by includeIf in the global gitconfig.
#
# Usage: content=$(build_profile_gitconfig "pro" "Bhaskar Jha" "bhaskar@email.com")
# ------------------------------------------------------------------------------
build_profile_gitconfig() {
    local label="$1"
    local name="$2"
    local email="$3"
    local sign_commits="${4:-0}"
    local key_path="${5:-$HOME/.ssh/id_ed25519_${label}}"

    # Convert key_path to portable tilde notation
    local portable_key="$key_path"
    if [[ "$key_path" == "$HOME/.ssh/"* ]] || [[ "$key_path" =~ (\.ssh/.*)$ ]]; then
        portable_key="~/.ssh/${key_path##*/}"
    elif [[ "$key_path" == "$HOME/"* ]]; then
        portable_key="~/${key_path#"$HOME"/}"
    fi
    local safe_ssh_key="$portable_key"
    if [[ "$safe_ssh_key" == *" "* ]]; then
        safe_ssh_key="\"${safe_ssh_key}\""
    fi

    # NOTE: `provider` and `provider_user` are NOT parameters of this function.
    # They are accessed via Bash's dynamic scoping from the calling function
    # `write_profile_gitconfig()`, which declares them as local variables.
    # This is intentional to keep the parameter list manageable.

    cat <<EOF
${GITSETU_MANAGED_START} Profile: ${label}
# Generated by gitsetu v${GITSETU_VERSION} on $(date +%Y-%m-%d)
# This config is auto-included when working in the '${label}' directory.

[user]
    name = ${name}
    email = ${email}
EOF

    if [[ "$sign_commits" == "1" ]]; then
        cat <<EOF
    signingkey = ${portable_key}.pub

[gpg]
    format = ssh

[commit]
    gpgsign = true
EOF
    fi

    cat <<EOF

[core]
    sshCommand = ssh -i ${safe_ssh_key}
EOF

    if [[ -n "${provider_user:-}" ]] && [[ -n "${provider:-}" ]]; then
        cat <<EOF

[credential "https://${provider}"]
    username = ${provider_user}
EOF
    fi

    cat <<EOF
${GITSETU_MANAGED_END} Profile: ${label}
EOF
}

# ------------------------------------------------------------------------------
# write_profile_gitconfig — Write a per-profile gitconfig file
#
# Creates: ~/.config/gitsetu/profiles/<label>.gitconfig
#
# Usage: write_profile_gitconfig "pro" "Bhaskar Jha" "bhaskar@email.com"
# ------------------------------------------------------------------------------
write_profile_gitconfig() {
    local label="$1"
    local name="$2"
    local email="$3"
    local sign_commits="${4:-0}"
    local key_path="${5:-$HOME/.ssh/id_ed25519_${label}}"
    local provider="${6:-}"
    local provider_user="${7:-}"
    local profile_path="$GITSETU_PROFILES_DIR/${label}.gitconfig"

    local content
    content=$(build_profile_gitconfig "$label" "$name" "$email" "$sign_commits" "$key_path")

    if [[ "$GITSETU_DRY_RUN" -eq 1 ]]; then
        print_info "[DRY RUN] Would create: $profile_path"
        return 0
    fi

    ensure_dirs
    printf '%s\n' "$content" > "$profile_path"
    print_success "Created profile config: $profile_path"
}

# ------------------------------------------------------------------------------
# write_profiles_conf — Write the profile registry file
#
# Format: label:email:directory (one per line)
# Used by the guard hook to validate identities.
#
# Usage: write_profiles_conf
# ------------------------------------------------------------------------------
write_profiles_conf() {
    if [[ "$GITSETU_DRY_RUN" -eq 1 ]]; then
        print_info "[DRY RUN] Would create: $GITSETU_PROFILES_CONF"
        return 0
    fi

    ensure_dirs

    local tmp_file
    tmp_file=$(mktemp "${GITSETU_PROFILES_CONF}.tmp.XXXXXX")
    GITSETU_CLEANUP_FILES+=("$tmp_file")

    # Write header
    cat > "$tmp_file" <<EOF
# gitsetu profile registry — generated on $(date +%Y-%m-%d)
# Format: label:email:directory:provider:sign_commits:key_path:provider_user
# Used by the pre-commit guard hook
EOF

    local i
    for (( i=0; i<PROFILE_COUNT; i++ )); do
        local label="${PROFILE_LABELS[$i]}"
        local email="${PROFILE_EMAILS[$i]}"
        local dir="${PROFILE_DIRS[$i]}"
        local provider="${PROFILE_PROVIDERS[$i]:-github.com}"
        local sign_commits="${PROFILE_SIGNS[$i]:-0}"
        local key_path="${PROFILE_KEYS[$i]:-~/.ssh/id_ed25519_${label}}"
        local provider_user="${PROFILE_USERS[$i]:-}"
        
        # We leave the email column empty in the registry to prevent dual-state desynchronization.
        # It will be dynamically parsed from profile.gitconfig at runtime.
        printf '%s::%s:%s:%s:%s:%s\n' "$label" "$dir" "$provider" "$sign_commits" "$key_path" "$provider_user" >> "$tmp_file"
        
        # Write the gitconfig (now with provider and provider_user)
        write_profile_gitconfig "$label" "${PROFILE_NAMES[$i]}" "${PROFILE_EMAILS[$i]}" "$sign_commits" "$key_path" "$provider" "$provider_user"
    done

    mv "$tmp_file" "$GITSETU_PROFILES_CONF"
    print_success "Created profile registry: $GITSETU_PROFILES_CONF"

    # Clean up orphaned profile configs
    if [[ -d "$GITSETU_PROFILES_DIR" ]]; then
        local pfile plabel pfound j
        for pfile in "$GITSETU_PROFILES_DIR"/*.gitconfig; do
            [[ -f "$pfile" ]] || continue
            plabel=$(basename "$pfile" .gitconfig)
            pfound=0
            for (( j=0; j<PROFILE_COUNT; j++ )); do
                if [[ "${PROFILE_LABELS[j]}" == "$plabel" ]]; then
                    pfound=1
                    break
                fi
            done
            if [[ "$pfound" -eq 0 ]]; then
                rm -f "$pfile"
            fi
        done
    fi
}
